version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    networks:
      - springboot-mysql-net
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: todolist
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  todolist:
    build: .
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080/tcp"
    networks:
      - springboot-mysql-net
    depends_on:
      - mysqldb
networks:
  springboot-mysql-net:
    driver: bridge
